### ISSUE TITLE
Using different Touchscreen / FSCU needed?

### ISSUE THREAD

**Issue by blongmon** [FriendlyStack/FriendlyStack#1]
Hi!
Is ist possible to look at the webinterface without a FSCU? I installed the System in a VM and after entering the unlock Code "FriendlyStack" nothing happend. The Page did not change and still say looked. 

Via SSH after manually using the decryptFriendlyStack script it says a Device "pstack" is all Ready there.
It seems it does not mount the Folders correctly. Is this because it is a VM without a FSCU? 

Second Question:
I have absolutely no clue About Arduinos so a silly Question: 
Is it possible to use another Touchscreen Display with FS? 
In Germany i can get a Arduino with this Touchscreen for 25€ 
https://www.waveshare.com/product/arduino/shields/wavesharer/2.8inch-tft-touch-shield.htm

Thanks in Advantage for answering my possible silly questions!

**Comment by dkalliv** [comment]
Hi blongmon,
it is possible to adapt FriendlyStack to work without a FSCU. This would however reduce the functionality (how are you going to start scanning documents or trigger a backup) and make FriendlyStack much less user friendly. I suggest that you invest in an Arduino and a display shield instead. Knowing that many people will be uncomfortable programing an Arduino themselves, the installation script will take care of this automatically (assuming the Arduino is plugged in during the installation).
You should however make sure that you buy the correct parts. While you can use other parts, you would have to adapt the Arduino firmware to fit your display shield and/or controller. While there are literally thousands of cheaper alternatives you should know what you are doing or you will spend many hours just to save a few Euros...
In Germany you could get the required parts from Mouser or Digi-Key (I'm sure there are plenty of other vendors).
www.mouser.de
Display Part Number: 485-1651
Arduino Part Number: 782-A000073

www.digikey.de
Display Part Number: 1528-1027-ND
Arduino Part Number: 1050-1041-ND

I hope this helps. Oh and FriendlyStack should work on VMs as long as they can handle USB passthrough...

**Comment by blongmon** [comment]
Hi dkalliv,
thanks for your response!

The backuptrigger could be done via webinterface. For scanning i prefer the method of just dropping the PDF to a SMB shared folder. With that done, the need for a Linux supported scanner would be eliminated. 

I played with Linux and my document scanner a little bit, but didn't succeed. It could be bad luck that the Plustek PS406U i have standing on my desk  is not supported by Linux. 
My Canon P-150 could be working but is away right now. If i can use that one to scan, i will invest in the Arduino + Shield to test.

**Comment by dkalliv** [comment]
I decided to enable network scanning (using a hot folder) and make the control unit optional. Also working on a cheaper and more powerful version for the control unit...

**Comment by dkalliv** [comment]
FriendlyStack kann now work without a Control Unit.
